### PR TITLE
Misc sparsevec cleanups

### PR DESCRIPTION
**Pull request by hlinnaka**
See commit messages for details

### CODE REVIEW

**Comment by ankane** [comment]
Thanks @hlinnaka! Incorporated much of this in the commit above (and prefer to keep the rest as-is).

One thing I'm still trying to decide is whether to store indices as 0-based or 1-based on-disk (since indices are 0-based in C and 1-based in SQL). Let me know if you have any thoughts.

**Comment by hlinnaka** [comment]
Ok. What is the reason for the 'unused' field? Is it reserved for future extensibility like I assumed?

**Comment by hlinnaka** [comment]
> One thing I'm still trying to decide is whether to store indices as 0-based or 1-based on-disk (since indices are 0-based in C and 1-based in SQL). Let me know if you have any thoughts.

No opinion. Just based on instinct I'd probably make them 0-based, but I could go either way.

**Comment by ankane** [comment]
Re `usused`: yes (and originally thought it was beneficial for alignment). Went ahead and merged the 2nd commit in b8bdf317f0a3c988c68d931b0324f60b5686067c.

Re numbering: that's the direction I was leaning as well, so made the switch in 78e5bcf22952ac1ca999f387d3ffc540ca9d8300.

**Pull request closed without merging**
