### PR TITLE
Fix checking the entry point's level

### PR DESCRIPTION
**Pull request by hlinnaka**
The entryPoint->level field in the HnswElement is uninitialized. Read the entryLevel from the metapage's entryLevel instead.

Fixes issue #439

### CODE REVIEW

**Comment by ankane** [comment]
Thanks @hlinnaka, great find! I think this can be solved with a smaller diff.

```diff
diff --git a/src/hnswutils.c b/src/hnswutils.c
index f7c0029..8ae7001 100644
--- a/src/hnswutils.c
+++ b/src/hnswutils.c
@@ -315,7 +315,10 @@ HnswGetMetaPageInfo(Relation index, int *m, HnswElement * entryPoint)
 	if (entryPoint != NULL)
 	{
 		if (BlockNumberIsValid(metap->entryBlkno))
+		{
 			*entryPoint = HnswInitElementFromBlock(metap->entryBlkno, metap->entryOffno);
+			(*entryPoint)->level = metap->entryLevel;
+		}
 		else
 			*entryPoint = NULL;
 	}
```

**Comment by hlinnaka** [comment]
Yeah, that works too. I was reluctant to do that, because it introduces a new "state" to which fields in HnswElement are valid. Currently:

a) Only blkno, offno, neighborPage, neighborOffno fields are valid.

b) In addition to those, `value` can be valid or not

c)  In addition to those, `neighbors` can be valid or not

This would make  entryPoint be in a state like a), but also `level` is valid. Maybe I'm overthinking this...

**Comment by hlinnaka** [comment]
Just noticed that I missed on reference to `entryPoint->level` in HnswFindElementNeighbors. I'm surprised valgrind didn't complain about that.

**Comment by ankane** [comment]
Agree it introduces a new state, but think it's fine for the entry point. `HnswEntryCandidate` loads the level in `HnswFindElementNeighbors`, so think that reference is fine.

**Pull request closed without merging**
