### PR TITLE
Use a simple array to hold non-closer elements in SelectNeighbors

### PR DESCRIPTION
**Pull request by hlinnaka**
The input is already ordered, so we don't need a heap to keep the order.

### CODE REVIEW

**Comment by jkatz** [comment]
@hlinnaka Do you have any rough performance stats based on this change?

**Comment by hlinnaka** [comment]
It's not significant, the pairingheap operations don't really show up in profiling.

**Comment by ankane** [comment]
Thanks @hlinnaka. Looking at the test failures across multiple CI runs, I'm not very confident this doesn't introduce a bug (but don't immediately see what it is).

**Comment by ankane** [comment]
I think the issue is `wdoff` isn't incremented after the last iteration.

**Comment by ankane** [comment]
Looks like that still didn't fix it, so reverted.

**Comment by ankane** [comment]
Found and fixed the issue in fa52511eaa90f1b1f3156e00bcc7cde4c56cbae2, so going to restore.

**Pull request closed without merging**
