### PR TITLE
Add Alpine Dockerfile

### PR DESCRIPTION
**Pull request by jramos**
This adds a Dockerfile for creating an Alpine build. The resulting image is ~80MB smaller than the Debian image.

### CODE REVIEW

**Comment by ankane** [comment]
Hi @jramos, thanks for the PR. I'd only like to support one Dockerfile right now, but this should be a useful reference for other users who are interested in it.

**Comment by SamuelMarks** [comment]
Thanks @jramos ; until the pgvector maintainers change their mind I've setup automated and scheduled releases to Docker Hub of the alpine variant - https://hub.docker.com/r/samuelmarks/pgvector-builds

**Comment by 0xMurage** [comment]
Adding this for future you/AI who will encounter headaches with builds:

Use clang and llvm 19 when building for pgvector v0.7.3+  with postgres 16+  i.e.

 `apk add --no-cache build-base clang19 llvm19 postgresql${PG_MAJOR}-dev `

**Comment by SamuelMarks** [comment]
@0xMurage good point, updated https://github.com/SamuelMarks/pgvector-builds https://hub.docker.com/r/samuelmarks/pgvector-builds

**Pull request closed without merging**
