### PR TITLE
Use blis for vector operations

### PR DESCRIPTION
**Pull request by maparent**
This is very tentative, needs benchmarks, documentation, etc.
But it should speed up many operations.
I was curious whether this is something you want to explore.
Regards

### CODE REVIEW

**Comment by ankane** [comment]
Hey @maparent, thanks for the PR! It's a neat idea. Would be good to see how performance compares for each of the distance calculations to understand if it's worth the extra complexity (the functions are currently vectorized with auto-vectorization, but not sure how it compares to BLIS).

**Comment by maparent** [comment]
First: delighted to hear you find this worth pursuing!
Second: What are your acceptance conditions?
Offhand, I think we'd want

1. Benchmarks
2. Git action to test the blis option
3. Some documentation

Do you see anything else?

**Comment by ankane** [comment]
That looks reasonable, but need to see if the performance justifies the complexity first.

**Comment by maparent** [comment]
One last comment: I also compared OpenMP, with even worse results on my (admittedly simplistic) test.

**Comment by mikeizbicki** [comment]
The real advantage of BLAS libraries is when you get to the level 3 (matrix-matrix) operations.  Matrix multiplies need a lot of optimizations to be fast (selecting the right version of strassen's algorithm, and setting appropriate block sizes for cache, etc), but vector-vector operations don't really need anything special because it's just a for loop.  I could see some uses for matrix inside postgres, in which case BLAS would be a huge win, but with just vectors it's not at all surprising to me that native optimizing compilers generate faster code.

**Comment by ankane** [comment]
Also, if it speeds up vector-matrix operations, there's a chance it could be useful for indexes, but probably won't be as straightforward as the changes above.

**Pull request closed without merging**
