### PR TITLE
Optimize the ivfflat cost estimate

### PR DESCRIPTION
**Pull request by fanfuxiaoran**
When table is toasted, assuming the index is also toasted, the 'numIndexPages' would be approximately equal to the 'rel->pages * ratio'

### CODE REVIEW

**Comment by ankane** [comment]
Hi @fanfuxiaoran, thanks for another PR. The index isn't toasted, so I think this makes the cost estimate more inaccurate (lower than needed). Is there a specific situation you're optimizing for?

**Comment by fanfuxiaoran** [comment]
>  Is there a specific situation you're optimizing for?

No, there is no specific case for the optimization.  I thought there should be one, but I cannot come up with one, as the cost model is too complicated. 

> The index isn't toasted, so I think this makes the cost estimate more inaccurate (lower than needed)

Thanks for your comments. You are right that this makes the cost estimate more inaccurate. But from my point of view, since sequence scan doesn't include the pages in the TOAST table, the index should also exclude that( pages in the toasted table) to make the planner choose the appropriate scan path.  While the estimated cost is far away from the actual cost, personally I think that is not a big problem as the cost model can make the planner do the right choice.

**Comment by ankane** [comment]
I think it's better to minimize the inaccuracy (lower the cost just enough so it's better than a sequence scan), since other index types may not be inaccurate. There's a previous discussion in #133 if you haven't seen it already.

I appreciate the suggestion, but want to stay with the current approach.

**Comment by jkatz** [comment]
For the archive, there may be some upstream PostgreSQL work on how we can improve cost estimation when performing a scan on a TOASTed column.

**Pull request closed without merging**
